INSERT INTO people (box_number, department) VALUES (1, "President's Office");
INSERT INTO people (box_number, department) VALUES (2, "Executive VP Academic Affairs");
INSERT INTO people (box_number, department) VALUES (3, "Bursar Operations");
INSERT INTO people (box_number, department) VALUES (4, "Finacial Services");
INSERT INTO people (box_number, department) VALUES (5, "Executive VP, Academic Affairs/CAO");
INSERT INTO people (box_number, department) VALUES (6, "College Communications/Planning");
INSERT INTO people (box_number, department) VALUES (7, "Student Activities");
INSERT INTO people (box_number, department) VALUES (8, "Dinning Services");
INSERT INTO people (box_number, department) VALUES (9, "Institutional Advancement");
INSERT INTO people (box_number, department) VALUES (10, "Career & Technical Education");
INSERT INTO people (box_number, department) VALUES (11, "Nerman Museum of Contemporary Art");
INSERT INTO people (box_number, department) VALUES (12, "Police Department");
INSERT INTO people (box_number, department) VALUES (13, "Bookstore");
INSERT INTO people (box_number, department) VALUES (14, "Performing Arts/Box Office");
INSERT INTO people (box_number, department) VALUES (15, "Hiersteiner Child Devlopment Center");
INSERT INTO people (box_number, department) VALUES (16, "Burlington Northern Santa Fe Railroad");
INSERT INTO people (box_number, department) VALUES (17, "Industrial Technology");
INSERT INTO people (box_number, department) VALUES (18, "Athletics & HPER Program");
INSERT INTO people (box_number, department) VALUES (19, "Science Division");
INSERT INTO people (box_number, department) VALUES (20, "Audio Visual Services");
INSERT INTO people (box_number, department) VALUES (21, "Billington Library");
INSERT INTO people (box_number, department) VALUES (22, "Collaboration Lab");
INSERT INTO people (box_number, department) VALUES (23, "Administrative Photography");
INSERT INTO people (box_number, department) VALUES (24, "Publications");
INSERT INTO people (box_number, department) VALUES (25, "Foundation/Institutional Advancement");
INSERT INTO people (box_number, department) VALUES (26, "Continuing Professional Education");
INSERT INTO people (box_number, department) VALUES (27, "Acad Tech Services - Computer Labs");
INSERT INTO people (box_number, department) VALUES (28, "Computer Science/Info Tech");
INSERT INTO people (box_number, department) VALUES (29, "Mathmatics Division");
INSERT INTO people (box_number, department) VALUES (30, "Int'l & Immigrant Student Services");
INSERT INTO people (box_number, department) VALUES (31, "Communications, Speech & Languages");
INSERT INTO people (box_number, department) VALUES (32, "KS Small Business Development");
INSERT INTO people (box_number, department) VALUES (33, "Continuing Education Operations");
INSERT INTO people (box_number, department) VALUES (34, "Community Services");
INSERT INTO people (box_number, department) VALUES (35, "AVP, Continuing Ed & Org Dev");
INSERT INTO people (box_number, department) VALUES (36, "Arts, Humanities & Social Sciences");
INSERT INTO people (box_number, department) VALUES (37, "Business Mgmt & Administration");
INSERT INTO people (box_number, department) VALUES (38, "Police Academy");
INSERT INTO people (box_number, department) VALUES (39, "Con't Ed/Comm Svs Scheduling");
INSERT INTO people (box_number, department) VALUES (40, "Veterans Services");
INSERT INTO people (box_number, department) VALUES (41, "Enrollment Management");
INSERT INTO people (box_number, department) VALUES (42, "Grants and Leadership");
INSERT INTO people (box_number, department) VALUES (43, "Staff Development");
INSERT INTO people (box_number, department) VALUES (44, "Accounting Services - Payrol");
INSERT INTO people (box_number, department) VALUES (45, "Accounts Payable");
INSERT INTO people (box_number, department) VALUES (46, "Human Resources");
INSERT INTO people (box_number, department) VALUES (47, "Testing & Assesment Services");
INSERT INTO people (box_number, department) VALUES (48, "Career Development Center");
INSERT INTO people (box_number, department) VALUES (49, "Counseling & Access Services");
INSERT INTO people (box_number, department) VALUES (50, "Student Financial Aid Services");
INSERT INTO people (box_number, department) VALUES (51, "Exec VP, Finance & Admin Services");
INSERT INTO people (box_number, department) VALUES (52, "Healthcare/ Wellness/ Fire Science");
INSERT INTO people (box_number, department) VALUES (53, "Vp, Student Success & Engagement");
INSERT INTO people (box_number, department) VALUES (54, "Warehouse/Postal Services")
INSERT INTO people (box_number, department) VALUES (55, "Director, Bursar Operations/ 3rd Party");
INSERT INTO people (box_number, department) VALUES (56, "Procurement Services");
INSERT INTO people (box_number, department) VALUES (57, "Campus Services");
INSERT INTO people (box_number, department) VALUES (58, "Outcomes Assesment");
INSERT INTO people (box_number, department) VALUES (59, "Document Services");
INSERT INTO people (box_number, department) VALUES (60, "CIO, Admin Computer Services");
INSERT INTO people (box_number, department) VALUES (61, "Olathe Center - ABE/ESL");
INSERT INTO people (box_number, department) VALUES (62, "Con't Ed & Comm Svcs Registration");
INSERT INTO people (box_number, department) VALUES (63, "Acad Tech Svcs - Drafting Labs");
INSERT INTO people (box_number, department) VALUES (64, "EMS");
INSERT INTO people (box_number, department) VALUES (65, "Educational Technology");
INSERT INTO people (box_number, department) VALUES (66, "Olathe Health Educational Center");
INSERT INTO people (box_number, department) VALUES (67, "West Park Campus");
INSERT INTO people (box_number, department) VALUES (68, "Video Services");
INSERT INTO people (box_number, department) VALUES (69, "Entrepreneurship Program");
INSERT INTO people (box_number, department) VALUES (71, "US Bank");
INSERT INTO people (box_number, department) VALUES (72, "Admin of Justice/Horticulture");
INSERT INTO people (box_number, department) VALUES (73, "AAC");
INSERT INTO people (box_number, department) VALUES (74, "Microcomputer Training");
INSERT INTO people (box_number, department) VALUES (75, "Ed Tech");
INSERT INTO people (box_number, department) VALUES (76, "Outreach/ STEM/ Early College");
INSERT INTO people (box_number, department) VALUES (77, "Student Ambassidors");
INSERT INTO people (box_number, department) VALUES (78, "Hospitality Management");
INSERT INTO people (box_number, department) VALUES (79, "Audit & Advisory Services");
INSERT INTO people (box_number, department) VALUES (80, "English, Writing & Journalism");
INSERT INTO people (box_number, department) VALUES (81, "Sustainability Initiatives");
INSERT INTO people (box_number, department) VALUES (82, "CLEAR");
INSERT INTO people (box_number, department) VALUES (83, "Dental Hygiene Program");
INSERT INTO people (box_number, department) VALUES (84, "General Counsel");
INSERT INTO people (box_number, department) VALUES (85, "Honors/Int'l Education");
INSERT INTO people (box_number, department) VALUES (86, "Nat'l Assoc of RR Sciences (NARS)");
INSERT INTO people (box_number, department) VALUES (87, "Benchmarking/Market Research");