INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (1, "President's Office", "Worley, Randi", "GEB", 112);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (2, "Executive VP Academic Affairs", "Demoronville, Yvonne", "GEB", 112);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (3, "Bursar Operations", "Morris, Brenda", "GEB", 115);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (4, "Finacial Services", "Russel, Chandra", "GEB", 152);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (5, "Executive VP, Academic Affairs/CAO", "Reed, Karen", "SCI", 128);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (6, "College Communications/Planning", "Swisher, Susan", "GEB", 140);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (7, "Student Activities", "Kurtz, Terri", "COM", 100);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (8, "Dinning Services", "Keating, Jean", "SC", 110);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (9, "Institutional Advancement", "Light, Mary McMullen", "GEB", 261);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (10, "Career & Technical Education", "Smethers, Dianne", "OCB", 157);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (11, "Nerman Museum of Contemporary Art", "Venkata, Hema", "NM", 214);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (12, "Police Department", "Swift, Aaron", "CC", 215);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (13, "Bookstore", "Schoenwandt, Kathy", "SC", 110);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (14, "Performing Arts/Box Office", "Wood, Ruby", "CC", 109);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (15, "Hiersteiner Child Devlopment Center", "Morris, Terry", "HCDC", 100);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (16, "Burlington Northern Santa Fe Railroad", "Rouse, Todd", "ITC", 127);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (17, "Industrial Technology", "Cody, Pat", "ATB", 123);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (18, "Athletics & HPER Program", "Petre, Betsy", "GYM", 116);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (19, "Science Division", "Bieberich, Lydia", "CLB", 339);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (20, "Audio Visual Services", "Swan, Adrian", "LIB", 125);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (21, "Billington Library", "Hodgson, Elaine", "LIB", 229);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (22, "Collaboration Lab", "Paterson, Drew", "OCB", 100);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (23, "Administrative Photography", "McSpadden, Susan", "LIB", 142);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (24, "Publications", "Tull, Melanie", "LIB", 141);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (25, "Foundation/Institutional Advancement", "Laddusaw, Terri", "CC", 207);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (26, "Continuing Professional Education", "Byrne, Jane", "RC", 159);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (27, "Acad Tech Services - Computer Labs", "Boyd, Barrett", "LIB", 227);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (28, "Computer Science/Info Tech", "Curtis, Joan", "RC", 332);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (29, "Mathmatics Division", "Karanevich, Reni", "CLB", 243);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (30, "Int'l & Immigrant Student Services", "Steinmetz, Kim", "COM", 306);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (31, "Communications, Speech & Languages", "Knopp, Shirley", "CC", 305);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (32, "KS Small Business Development", "Clickner, Ellen", "RC", 240);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (33, "Continuing Education Operations", "Koller, Karen", "RC", 148);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (34, "Community Services", "Baron, Lauren", "RC", 159);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (35, "AVP, Continuing Ed & Org Dev", "Hoffman, Susan", "RC", 152);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (36, "Arts, Humanities & Social Sciences", "Chestnut, Dee", "OCB", 261);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (37, "Business Mgmt & Administration", "Hanover, Mary", "OCB", 272);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (38, "Police Academy", "Islam, Tia", "PA", 103);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (39, "Con't Ed/Comm Svs Scheduling", "Hunt, Anne", "RC", 140);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (40, "Veterans Services", "Lopez, Hidy", "COM", 305);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (41, "Enrollment Management", "Livingston, Georgia", "SC", 319);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (42, "Grants and Leadership", "Wu, Selina", "LIB", 355);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (43, "Staff Development", "Sinn, Elaine", "GEB", 275);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (44, "Accounting Services - Payrol", "Blake, Heidi", "GEB", 154);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (45, "Accounts Payable", "Cox, Kristen", "CSB", 165);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (46, "Human Resources", "Kindig, Robin", "GEB", 274);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (47, "Testing & Assesment Services", "Wirsig, Sharon", "SC", 334);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (48, "Career Development Center", "Gard, Carol", "SC", 215);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (49, "Counseling & Access Services", "Gamble, Pat", "SC", 202);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (50, "Student Financial Aid Services", "Jost, Ashley", "SC", 311);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (51, "Exec VP, Finance & Admin Services", "Nelson, Linda", "GEB", 161);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (52, "Healthcare/ Wellness/ Fire Science", "Christie, Parri", "CLB", 243);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (53, "Vp, Student Success & Engagement", "Cross, Jody", "SC", 325);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (54, "Warehouse/Postal Services", "Knoettgen, Paul", "WH", 108)
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (55, "Director, Bursar Operations/ 3rd Party", "Callahan, Gayle", "GEB", 117);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (56, "Procurement Services", "Freeman, Berni", "CSB", 170);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (57, "Campus Services", "Metsinger, Pat", "CSB", 101);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (58, "Outcomes Assesment", "Loomis, Liz", "GEB", 262);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (59, "Document Services", "Tiruneh, Hanna", "CSB", 161);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (60, "CIO, Admin Computer Services", "Boyer, Angela", "RC", 247);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (61, "Olathe Center - ABE/ESL", "Knight, Beth", "OHEC", 133);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (62, "Con't Ed & Comm Svcs Registration", "Riggs, Joann", "RC", 173);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (63, "Acad Tech Svcs - Drafting Labs", "Butler, Tony", "ITC", 190);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (64, "EMS", "Hambright, Carrie", "SCI", 110);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (65, "Educational Technology", "Ramirez, Beth", "LIB", 353);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (66, "Olathe Health Educational Center", "Callaghan, Judy", "OHEC", 221);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (67, "West Park Campus", "Belford, Stephanie", "WPK", 121);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (68, "Video Services", "NA", "LIB", 147);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (69, "Entrepreneurship Program", "Grandgenett, Caren", "RC", 240);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (71, "US Bank", "NA", "SC", 108);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (72, "Admin of Justice/Horticulture", "Galbrecht, Frank", "PA", 135);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (73, "AAC", "Sweeney, Maria", "OCB", 304);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (74, "Microcomputer Training", "Caselman, Valerie", "RC", 246);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (75, "Ed Tech", "Lovitt, Ed", "LIB", 375);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (76, "Outreach/ STEM/ Early College", "Rader, Sheila", "GEB", 252);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (77, "Student Ambassidors", "Simeon, Jean", "CC", 107);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (78, "Hospitality Management", "Sparks, Carol", "HCA", 103);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (79, "Audit & Advisory Services", "McLeod, Cheryl", "CC", 205);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (80, "English, Writing & Journalism", "Byfield, Kelly", "CC", 305);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (81, "Sustainability Initiatives", "Anton, Krystal", "OCB", 157);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (82, "CLEAR", "Huntington, Anne", "COM", 312);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (83, "Dental Hygiene Program", "Wilkerson, Denise", "SCI", 201);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (84, "General Counsel", "Wilson, Tanya", "GEB", 138);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (85, "Honors/Int'l Education", "Shuckman, Nellie", "COM", 201);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (86, "Nat'l Assoc of RR Sciences (NARS)", "McGarvey, Susan", "ITC", 112);
INSERT INTO people (box_number, department, contact_name, building_location, room_number) VALUES (87, "Benchmarking/Market Research", "Guthrie, Lou", "GEB", 211);